model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash-preview
      drop_params: true
    api_key: os.environ/OPENAI_API_KEY
    tags: ["text", "image", "audio", "video", "pdf"]
  - model_name: embedding
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GOOGLE_API_KEY
      drop_params: true
